Repository openebs/cstor, pull requests merged in 2020-05, with the labels that each got.

#302 refact(build): make the docker images configurable
  .travis.yml
  Dockerfile
  build_image.sh
  docker/Dockerfile
  docker/Dockerfile.arm64
  docker/Dockerfile.base
  docker/Dockerfile.base.arm64
  docker/push
Labels: Maintenance

#304 refactor(travis): fixing travis for tagging downstream repo
  .travis.yml
Labels: Maintenance

#305 refactor(build): trim leading v from image tag
  docker/push
Labels: Maintenance

#306 reafact(build): fixing git-release file to ignore error if tag already exists
  buildscripts/git-release
Labels: Maintenance

#307 cherrypick(refact,build): fixing git-release file to ignore error if tag already exists
  .travis.yml
  buildscripts/git-release
Labels: Maintenance

#308 fix(build): installing jq in travis build
  .travis.yml
Labels: Maintenance

#311 doc(changelog): changelog for 1.10.0
  CHANGELOG.md
Labels: documentation

#309 fix(cstor): Fix the value of CPU_SEQID. Fixes crash on arm64, optimization on amd64.
  changelogs/unreleased/309-sgielen
  include/sys/zfs_context.h
Labels: bug

#312 refact(travis): adding email address for travis build notification
  .travis.yml
Labels: Maintenance

#310 fix(arm,build): changing ubuntu version in ARM cstor-base image
  docker/Dockerfile.base.arm64
Labels: Maintenance, bug
